### ISSUE TITLE
Recipe result modal not fully fitting on page

### ISSUE THREAD

**Issue by haleymnatz** [space-jammers/vegme#238]
Recipe result modal still cut off at bottom if recipe has many ingredients.

**Comment by lnzd17** [comment]
@haleymnatz 

- could we also remove the grey border that appears on upon click on the card?
- is this ticket to fix the modal cutting off for both mobile and desktop? Is the goal to have the modal fill the entire screen?
- one suggestion - what if the modal popups up on on desktop only? It may make sense to have the ingredients just drop down as before on mobile (less clicking in and out of stuff on mobile may be a nicer UI experience. The drop down happens quickly without taking attention away)
